-- Update students table with comprehensive fields
USE school;

-- Add new columns to existing students table
ALTER TABLE students 
ADD COLUMN roll VARCHAR(50) AFTER name,
ADD COLUMN className VARCHAR(100) AFTER roll_no,
ADD COLUMN nicId VARCHAR(50) AFTER dob,
ADD COLUMN srNo VARCHAR(50) AFTER nicId,
ADD COLUMN aadharNumber VARCHAR(20) AFTER srNo,
ADD COLUMN fatherName VARCHAR(255) AFTER parent_name,
ADD COLUMN motherName VARCHAR(255) AFTER fatherName,
ADD COLUMN socialCategory VARCHAR(100) AFTER gender,
ADD COLUMN religion VARCHAR(100) AFTER socialCategory,
ADD COLUMN motherTongue VARCHAR(100) AFTER religion,
ADD COLUMN ruralUrban ENUM('Rural', 'Urban') AFTER motherTongue,
ADD COLUMN habitationLocality VARCHAR(255) AFTER ruralUrban,
ADD COLUMN dateOfAdmission DATE AFTER habitationLocality,
ADD COLUMN admissionNumberSrNo VARCHAR(100) AFTER dateOfAdmission,
ADD COLUMN belongToBpl BOOLEAN DEFAULT FALSE AFTER admissionNumberSrNo,
ADD COLUMN belongToDisadvantagedGroup BOOLEAN DEFAULT FALSE AFTER belongToBpl,
ADD COLUMN gettingFreeEducation BOOLEAN DEFAULT FALSE AFTER belongToDisadvantagedGroup,
ADD COLUMN studyInClass VARCHAR(100) AFTER gettingFreeEducation,
ADD COLUMN studyingInClass VARCHAR(100) AFTER studyInClass,
ADD COLUMN classStudiedInPrevYear VARCHAR(100) AFTER studyingInClass,
ADD COLUMN ifInClass1StatusOfPreviousYear VARCHAR(100) AFTER classStudiedInPrevYear,
ADD COLUMN daysChildAttendedSchoolInPrevYear INT AFTER ifInClass1StatusOfPreviousYear,
ADD COLUMN mediumOfInstruction VARCHAR(100) AFTER daysChildAttendedSchoolInPrevYear,
ADD COLUMN typeOfDisability VARCHAR(100) AFTER mediumOfInstruction,
ADD COLUMN facilitiesReceivedByCWSN TEXT AFTER typeOfDisability,
ADD COLUMN noOfUniformSets INT DEFAULT 0 AFTER facilitiesReceivedByCWSN,
ADD COLUMN freeTextBooks BOOLEAN DEFAULT FALSE AFTER noOfUniformSets,
ADD COLUMN freeTransport BOOLEAN DEFAULT FALSE AFTER freeTextBooks,
ADD COLUMN freeEscort BOOLEAN DEFAULT FALSE AFTER freeTransport,
ADD COLUMN mdmBeneficiary BOOLEAN DEFAULT FALSE AFTER freeEscort,
ADD COLUMN freeHostelFacility BOOLEAN DEFAULT FALSE AFTER mdmBeneficiary,
ADD COLUMN childAttendedSpecialTraining BOOLEAN DEFAULT FALSE AFTER freeHostelFacility,
ADD COLUMN inLastExaminationAppeared VARCHAR(100) AFTER childAttendedSpecialTraining,
ADD COLUMN inLastExaminationPassed VARCHAR(100) AFTER inLastExaminationAppeared,
ADD COLUMN inLastExaminationMarks VARCHAR(50) AFTER inLastExaminationPassed,
ADD COLUMN stream VARCHAR(100) AFTER inLastExaminationMarks,
ADD COLUMN tradeSector VARCHAR(100) AFTER stream,
ADD COLUMN ironFolicAcidTablets BOOLEAN DEFAULT FALSE AFTER tradeSector,
ADD COLUMN dewormingTablets BOOLEAN DEFAULT FALSE AFTER ironFolicAcidTablets,
ADD COLUMN vitaminASupplement BOOLEAN DEFAULT FALSE AFTER dewormingTablets,
ADD COLUMN mobileNumber VARCHAR(20) AFTER vitaminASupplement,
ADD COLUMN emailAddress VARCHAR(255) AFTER mobileNumber,
ADD COLUMN totalFees DECIMAL(10,2) DEFAULT 0.00 AFTER emailAddress,
ADD COLUMN paidFees DECIMAL(10,2) DEFAULT 0.00 AFTER totalFees,
ADD COLUMN pendingFees DECIMAL(10,2) DEFAULT 0.00 AFTER paidFees,
ADD COLUMN lastFeePaymentDate DATE AFTER pendingFees,
ADD COLUMN nextFeeDueDate DATE AFTER lastFeePaymentDate;
